from inui.elements import *
from inui.svg import *

Html(
    data=(
        Body(
            data=(
                Ul(
                    classs="""sticky-social-bar""",
                    data=(
                        Li(
                            classs="""social-icon""",
                            data=(
                                A(
                                    href="""#""",
                                    data=(
                                        I(
                                            classs="""fa fa-facebook""",
                                            aria_hidden="""true""",
                                        ),
                                        Span(
                                            classs="""social-icon-text""",
                                            data=("""Facebook""",),
                                        ),
                                    ),
                                ),
                            ),
                        ),
                        Li(
                            classs="""social-icon""",
                            data=(
                                A(
                                    href="""#""",
                                    data=(
                                        I(
                                            classs="""fa fa-twitter""",
                                            aria_hidden="""true""",
                                        ),
                                        Span(
                                            classs="""social-icon-text""",
                                            data=("""Twitter""",),
                                        ),
                                    ),
                                ),
                            ),
                        ),
                        Li(
                            classs="""social-icon""",
                            data=(
                                A(
                                    href="""#""",
                                    data=(
                                        I(
                                            classs="""fa fa-linkedin""",
                                            aria_hidden="""true""",
                                        ),
                                        Span(
                                            classs="""social-icon-text""",
                                            data=("""Linkedin""",),
                                        ),
                                    ),
                                ),
                            ),
                        ),
                        Li(
                            classs="""social-icon""",
                            data=(
                                A(
                                    href="""#""",
                                    data=(
                                        I(
                                            classs="""fa fa-youtube""",
                                            aria_hidden="""true""",
                                        ),
                                        Span(
                                            classs="""social-icon-text""",
                                            data=("""Youtube""",),
                                        ),
                                    ),
                                ),
                            ),
                        ),
                        Li(
                            classs="""social-icon""",
                            data=(
                                A(
                                    href="""#""",
                                    data=(
                                        I(
                                            classs="""fa fa-instagram""",
                                            aria_hidden="""true""",
                                        ),
                                        Span(
                                            classs="""social-icon-text""",
                                            data=("""Instagram""",),
                                        ),
                                    ),
                                ),
                            ),
                        ),
                        Li(
                            classs="""social-icon""",
                            data=(
                                A(
                                    href="""#""",
                                    data=(
                                        I(
                                            classs="""fa fa-pinterest-p""",
                                            aria_hidden="""true""",
                                        ),
                                        Span(
                                            classs="""social-icon-text""",
                                            data=("""Pinterest""",),
                                        ),
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
            )
        ),
    )
)
