from inui.elements import *
from inui.svg import *

Html(
    data=(
        Body(
            data=(
                Div(
                    id="""engadget-footer-sitemap-container""",
                    data=(
                        Footer(
                            id="""engadget-footer-sitemap""",
                            data=(
                                Div(
                                    classs="""links""",
                                    data=(
                                        Div(
                                            classs="""link-column""",
                                            data=(
                                                Ul(
                                                    classs="""menu vertical""",
                                                    data=(
                                                        Li(
                                                            data=(
                                                                A(
                                                                    href="""#""",
                                                                    data=("""One""",),
                                                                ),
                                                            )
                                                        ),
                                                        Li(
                                                            data=(
                                                                A(
                                                                    href="""#""",
                                                                    data=("""Two""",),
                                                                ),
                                                            )
                                                        ),
                                                        Li(
                                                            data=(
                                                                A(
                                                                    href="""#""",
                                                                    data=("""Three""",),
                                                                ),
                                                            )
                                                        ),
                                                        Li(
                                                            data=(
                                                                A(
                                                                    href="""#""",
                                                                    data=("""Four""",),
                                                                ),
                                                            )
                                                        ),
                                                    ),
                                                ),
                                            ),
                                        ),
                                        Div(
                                            classs="""link-column""",
                                            data=(
                                                Ul(
                                                    classs="""menu vertical""",
                                                    data=(
                                                        Li(
                                                            data=(
                                                                A(
                                                                    href="""#""",
                                                                    data=("""One""",),
                                                                ),
                                                            )
                                                        ),
                                                        Li(
                                                            data=(
                                                                A(
                                                                    href="""#""",
                                                                    data=("""Two""",),
                                                                ),
                                                            )
                                                        ),
                                                        Li(
                                                            data=(
                                                                A(
                                                                    href="""#""",
                                                                    data=("""Three""",),
                                                                ),
                                                            )
                                                        ),
                                                        Li(
                                                            data=(
                                                                A(
                                                                    href="""#""",
                                                                    data=("""Four""",),
                                                                ),
                                                            )
                                                        ),
                                                    ),
                                                ),
                                            ),
                                        ),
                                        Div(
                                            classs="""link-column""",
                                            data=(
                                                Ul(
                                                    classs="""menu vertical""",
                                                    data=(
                                                        Li(
                                                            data=(
                                                                A(
                                                                    href="""#""",
                                                                    data=("""One""",),
                                                                ),
                                                            )
                                                        ),
                                                        Li(
                                                            data=(
                                                                A(
                                                                    href="""#""",
                                                                    data=("""Two""",),
                                                                ),
                                                            )
                                                        ),
                                                        Li(
                                                            data=(
                                                                A(
                                                                    href="""#""",
                                                                    data=("""Three""",),
                                                                ),
                                                            )
                                                        ),
                                                        Li(
                                                            data=(
                                                                A(
                                                                    href="""#""",
                                                                    data=("""Four""",),
                                                                ),
                                                            )
                                                        ),
                                                    ),
                                                ),
                                            ),
                                        ),
                                        Div(
                                            classs="""link-column""",
                                            data=(
                                                Ul(
                                                    classs="""menu vertical""",
                                                    data=(
                                                        Li(
                                                            data=(
                                                                A(
                                                                    href="""#""",
                                                                    data=("""One""",),
                                                                ),
                                                            )
                                                        ),
                                                        Li(
                                                            data=(
                                                                A(
                                                                    href="""#""",
                                                                    data=("""Two""",),
                                                                ),
                                                            )
                                                        ),
                                                        Li(
                                                            data=(
                                                                A(
                                                                    href="""#""",
                                                                    data=("""Three""",),
                                                                ),
                                                            )
                                                        ),
                                                        Li(
                                                            data=(
                                                                A(
                                                                    href="""#""",
                                                                    data=("""Four""",),
                                                                ),
                                                            )
                                                        ),
                                                    ),
                                                ),
                                            ),
                                        ),
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
                Div(
                    id="""engadget-footer-social-container""",
                    data=(
                        Footer(
                            id="""engadget-footer-social""",
                            data=(
                                Div(
                                    classs="""footer-left""",
                                    data=(
                                        Div(
                                            classs="""newsletter""",
                                            data=(
                                                H6(
                                                    data=(
                                                        """Sign up for our newsletter""",
                                                    )
                                                ),
                                                Div(
                                                    classs="""input-group""",
                                                    data=(
                                                        Input(
                                                            classs="""input-group-field""",
                                                            typee="""email""",
                                                            placeholder="""Email address""",
                                                        ),
                                                        Div(
                                                            classs="""input-group-button""",
                                                            data=(
                                                                Input(
                                                                    typee="""submit""",
                                                                    classs="""button""",
                                                                    value="""Submit""",
                                                                ),
                                                            ),
                                                        ),
                                                    ),
                                                ),
                                            ),
                                        ),
                                    ),
                                ),
                                Div(
                                    classs="""footer-right""",
                                    data=(
                                        H6(data=("""Follow us""",)),
                                        I(
                                            classs="""fa fa-facebook-square fa-3x""",
                                            aria_hidden="""true""",
                                        ),
                                        I(
                                            classs="""fa fa-twitter-square fa-3x""",
                                            aria_hidden="""true""",
                                        ),
                                        I(
                                            classs="""fa fa-google-plus-square fa-3x""",
                                            aria_hidden="""true""",
                                        ),
                                        I(
                                            classs="""fa fa-linkedin-square fa-3x""",
                                            aria_hidden="""true""",
                                        ),
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
                Div(
                    id="""engadget-footer-contact-details-container""",
                    data=(
                        Footer(
                            id="""engadget-footer-contact-details""",
                            data=(
                                Div(
                                    classs="""footer-left""",
                                    data=(
                                        Div(
                                            classs="""contact-details""",
                                            data=(
                                                Ul(
                                                    data=(
                                                        Li(
                                                            data=(
                                                                Img(
                                                                    classs="""thumbnail""",
                                                                    src="""https://placehold.it/80""",
                                                                ),
                                                            )
                                                        ),
                                                        Li(
                                                            data=(
                                                                I(
                                                                    classs="""fa fa-phone fa-lg""",
                                                                    aria_hidden="""true""",
                                                                ),
                                                            )
                                                        ),
                                                        Li(
                                                            data=(
                                                                A(
                                                                    data_toggle="""animatedModal10""",
                                                                    data=(
                                                                        I(
                                                                            classs="""fa fa-envelope-o""",
                                                                            aria_hidden="""true""",
                                                                        ),
                                                                    ),
                                                                ),
                                                            )
                                                        ),
                                                        Li(
                                                            data=(
                                                                I(
                                                                    classs="""fa fa-map-marker fa-lg""",
                                                                    aria_hidden="""true""",
                                                                ),
                                                            )
                                                        ),
                                                    )
                                                ),
                                            ),
                                        ),
                                    ),
                                ),
                                Div(
                                    classs="""footer-right""",
                                    data=(
                                        Ul(
                                            classs="""menu align-right""",
                                            data=(
                                                Li(
                                                    data=(
                                                        A(
                                                            href="""#""",
                                                            data=("""One""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        A(
                                                            href="""#""",
                                                            data=("""Two""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        A(
                                                            href="""#""",
                                                            data=("""Three""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        A(
                                                            href="""#""",
                                                            data=("""Four""",),
                                                        ),
                                                    )
                                                ),
                                            ),
                                        ),
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
            )
        ),
    )
)
