from inui.elements import *
from inui.svg import *

Html(
    data=(
        Body(
            data=(
                Div(
                    classs="""header-grid""",
                    data=(
                        Div(
                            id="""b1""",
                            classs="""block""",
                        ),
                        Div(
                            id="""b2""",
                            classs="""block""",
                        ),
                        Div(
                            id="""b3""",
                            classs="""block""",
                        ),
                        Div(
                            id="""b4""",
                            classs="""block""",
                        ),
                        Div(
                            classs="""bottom-block""",
                            data=(
                                Div(
                                    id="""b5""",
                                    classs="""block""",
                                ),
                                Div(
                                    id="""b6""",
                                    classs="""block""",
                                ),
                                Div(
                                    id="""b7""",
                                    classs="""block""",
                                ),
                            ),
                        ),
                    ),
                ),
            )
        ),
    )
)
