from inui.elements import *
from inui.svg import *

Html(
    data=(
        Body(
            data=(
                Div(
                    classs="""featured-article-side-links""",
                    data=(
                        Div(
                            classs="""row collapse""",
                            data=(
                                Div(
                                    classs="""small-12 medium-6 columns""",
                                    data=(
                                        A(
                                            href="""#""",
                                            data=(
                                                Div(
                                                    classs="""featured-article-big""",
                                                    data=(
                                                        Div(
                                                            classs="""featured-article-tag""",
                                                            data=(
                                                                Span(
                                                                    classs="""label""",
                                                                    data=("""News""",),
                                                                ),
                                                            ),
                                                        ),
                                                        Div(
                                                            classs="""featured-article-text""",
                                                            data=(
                                                                P(
                                                                    classs="""featured-article-title""",
                                                                    data=(
                                                                        """Article Title Here """,
                                                                        Span(
                                                                            classs="""author""",
                                                                            data=(
                                                                                """by Jane Doe""",
                                                                            ),
                                                                        ),
                                                                    ),
                                                                ),
                                                                P(
                                                                    data=(
                                                                        """Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero quasi quae cum itaque quis soluta quaerat adipisci qui ex, laudantium consequuntur porro perferendis a laboriosam.""",
                                                                    )
                                                                ),
                                                                A(
                                                                    href="""#""",
                                                                    data=(
                                                                        """Read More >""",
                                                                    ),
                                                                ),
                                                            ),
                                                        ),
                                                    ),
                                                ),
                                            ),
                                        ),
                                    ),
                                ),
                                Div(
                                    classs="""medium-2 columns hide-for-small-only""",
                                    data=(
                                        Div(
                                            classs="""featured-article-small-container""",
                                            data=(
                                                A(
                                                    href="""#""",
                                                    data=(
                                                        Div(
                                                            classs="""featured-article-small""",
                                                            data=(
                                                                Div(
                                                                    classs="""featured-article-tag""",
                                                                    data=(
                                                                        Span(
                                                                            classs="""label""",
                                                                            data=(
                                                                                """News""",
                                                                            ),
                                                                        ),
                                                                    ),
                                                                ),
                                                                Div(
                                                                    classs="""featured-article-text""",
                                                                    data=(
                                                                        P(
                                                                            classs="""featured-article-title""",
                                                                            data=(
                                                                                """Another Article Title Here""",
                                                                            ),
                                                                        ),
                                                                    ),
                                                                ),
                                                            ),
                                                        ),
                                                    ),
                                                ),
                                                A(
                                                    href="""#""",
                                                    data=(
                                                        Div(
                                                            classs="""featured-article-small""",
                                                            data=(
                                                                Div(
                                                                    classs="""featured-article-tag""",
                                                                    data=(
                                                                        Span(
                                                                            classs="""label""",
                                                                            data=(
                                                                                """News""",
                                                                            ),
                                                                        ),
                                                                    ),
                                                                ),
                                                                Div(
                                                                    classs="""featured-article-text""",
                                                                    data=(
                                                                        P(
                                                                            classs="""featured-article-title""",
                                                                            data=(
                                                                                """Another Article Title Here""",
                                                                            ),
                                                                        ),
                                                                    ),
                                                                ),
                                                            ),
                                                        ),
                                                    ),
                                                ),
                                                A(
                                                    href="""#""",
                                                    data=(
                                                        Div(
                                                            classs="""featured-article-small""",
                                                            data=(
                                                                Div(
                                                                    classs="""featured-article-tag""",
                                                                    data=(
                                                                        Span(
                                                                            classs="""label""",
                                                                            data=(
                                                                                """News""",
                                                                            ),
                                                                        ),
                                                                    ),
                                                                ),
                                                                Div(
                                                                    classs="""featured-article-text""",
                                                                    data=(
                                                                        P(
                                                                            classs="""featured-article-title""",
                                                                            data=(
                                                                                """Another Article Title Here""",
                                                                            ),
                                                                        ),
                                                                    ),
                                                                ),
                                                            ),
                                                        ),
                                                    ),
                                                ),
                                            ),
                                        ),
                                    ),
                                ),
                                Div(
                                    classs="""small-12 medium-4 columns featured-article-links-container""",
                                    data=(
                                        Div(
                                            classs="""featured-article-links-header""",
                                            data=(
                                                """
        Top Stories
      """,
                                            ),
                                        ),
                                        Div(
                                            classs="""featured-article-links""",
                                            data=(
                                                A(
                                                    href="""#""",
                                                    data=("""Article Title Here""",),
                                                ),
                                            ),
                                        ),
                                        Div(
                                            classs="""featured-article-links""",
                                            data=(
                                                A(
                                                    href="""#""",
                                                    data=("""Article Title Here""",),
                                                ),
                                            ),
                                        ),
                                        Div(
                                            classs="""featured-article-links""",
                                            data=(
                                                A(
                                                    href="""#""",
                                                    data=("""Article Title Here""",),
                                                ),
                                            ),
                                        ),
                                        Div(
                                            classs="""featured-article-links""",
                                            data=(
                                                A(
                                                    href="""#""",
                                                    data=("""Article Title Here""",),
                                                ),
                                            ),
                                        ),
                                        Div(
                                            classs="""featured-article-links""",
                                            data=(
                                                A(
                                                    href="""#""",
                                                    data=("""Article Title Here""",),
                                                ),
                                            ),
                                        ),
                                        Div(
                                            classs="""featured-article-links""",
                                            data=(
                                                A(
                                                    href="""#""",
                                                    data=("""Article Title Here""",),
                                                ),
                                            ),
                                        ),
                                        Div(
                                            classs="""featured-article-links""",
                                            data=(
                                                A(
                                                    href="""#""",
                                                    data=("""Article Title Here""",),
                                                ),
                                            ),
                                        ),
                                        Div(
                                            classs="""featured-article-links""",
                                            data=(
                                                A(
                                                    href="""#""",
                                                    data=("""Article Title Here""",),
                                                ),
                                            ),
                                        ),
                                        Div(
                                            classs="""featured-article-links""",
                                            data=(
                                                A(
                                                    href="""#""",
                                                    data=("""Article Title Here""",),
                                                ),
                                            ),
                                        ),
                                        Div(
                                            classs="""featured-article-links""",
                                            data=(
                                                A(
                                                    href="""#""",
                                                    data=("""Article Title Here""",),
                                                ),
                                            ),
                                        ),
                                        Div(
                                            classs="""featured-article-links""",
                                            data=(
                                                A(
                                                    href="""#""",
                                                    data=("""Article Title Here""",),
                                                ),
                                            ),
                                        ),
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
            )
        ),
    )
)
