from inui.elements import *
from inui.svg import *

Html(
    data=(
        Body(
            data=(
                Div(
                    classs="""product-filters""",
                    data=(
                        Ul(
                            classs="""mobile-product-filters vertical menu show-for-small-only""",
                            data_accordion_menu="",
                            data=(
                                Li(
                                    data=(
                                        A(
                                            href="""#""",
                                            data=(H2(data=("""Products""",)),),
                                        ),
                                        Ul(
                                            classs="""vertical menu""",
                                            data_accordion_menu="",
                                            data=(
                                                Li(
                                                    classs="""product-filters-tab""",
                                                    data=(
                                                        A(
                                                            href="""#""",
                                                            data=("""Category""",),
                                                        ),
                                                        Ul(
                                                            classs="""categories-menu menu vertical nested is-active""",
                                                            data=(
                                                                A(
                                                                    href="""#""",
                                                                    classs="""clear-all""",
                                                                    id="""category-clear-all""",
                                                                    data=(
                                                                        """Clear All""",
                                                                    ),
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            classs="""category-clear-selection""",
                                                                            id="""category-checkbox1""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""category-checkbox1""",
                                                                            data=(
                                                                                """Category 1""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            classs="""category-clear-selection""",
                                                                            id="""category-checkbox2""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""category-checkbox2""",
                                                                            data=(
                                                                                """Category 2""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            classs="""category-clear-selection""",
                                                                            id="""category-checkbox3""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""category-checkbox3""",
                                                                            data=(
                                                                                """Category 3""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            classs="""category-clear-selection""",
                                                                            id="""category-checkbox4""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""category-checkbox4""",
                                                                            data=(
                                                                                """Category 4""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            classs="""category-clear-selection""",
                                                                            id="""category-checkbox5""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""category-checkbox5""",
                                                                            data=(
                                                                                """Category 5""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            classs="""category-clear-selection""",
                                                                            id="""category-checkbox6""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""category-checkbox6""",
                                                                            data=(
                                                                                """Category 6""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            classs="""category-clear-selection""",
                                                                            id="""category-checkbox7""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""category-checkbox7""",
                                                                            data=(
                                                                                """Category 7""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            classs="""category-clear-selection""",
                                                                            id="""category-checkbox8""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""category-checkbox8""",
                                                                            data=(
                                                                                """Category 8""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            classs="""category-clear-selection""",
                                                                            id="""category-checkbox9""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""category-checkbox9""",
                                                                            data=(
                                                                                """Category 9""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            classs="""category-clear-selection""",
                                                                            id="""category-checkbox10""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""category-checkbox10""",
                                                                            data=(
                                                                                """Category 10""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            classs="""category-clear-selection""",
                                                                            id="""category-checkbox11""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""category-checkbox11""",
                                                                            data=(
                                                                                """Category 11""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            classs="""category-clear-selection""",
                                                                            id="""category-checkbox12""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""category-checkbox12""",
                                                                            data=(
                                                                                """Category 12""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            classs="""category-clear-selection""",
                                                                            id="""category-checkbox13""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""category-checkbox13""",
                                                                            data=(
                                                                                """Category 13""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            classs="""category-clear-selection""",
                                                                            id="""category-checkbox14""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""category-checkbox14""",
                                                                            data=(
                                                                                """Category 14""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            classs="""category-clear-selection""",
                                                                            id="""category-checkbox15""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""category-checkbox15""",
                                                                            data=(
                                                                                """Category 15""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                            ),
                                                        ),
                                                    ),
                                                ),
                                                Li(
                                                    classs="""product-filters-tab""",
                                                    data=(
                                                        A(
                                                            href="""#""",
                                                            data=("""Size""",),
                                                        ),
                                                        Ul(
                                                            classs="""categories-menu menu vertical nested is-active""",
                                                            data=(
                                                                A(
                                                                    href="""#""",
                                                                    classs="""clear-all""",
                                                                    id="""size-clear-all""",
                                                                    data=(
                                                                        """Clear All""",
                                                                    ),
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            id="""size-checkbox1""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""size-checkbox1""",
                                                                            data=(
                                                                                """Small""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            id="""size-checkbox2""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""size-checkbox2""",
                                                                            data=(
                                                                                """Medium""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            id="""size-checkbox3""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""size-checkbox3""",
                                                                            data=(
                                                                                """Large""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            id="""size-checkbox3""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""size-checkbox3""",
                                                                            data=(
                                                                                """X-Large""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            id="""size-checkbox3""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""size-checkbox3""",
                                                                            data=(
                                                                                """XX-Large""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                            ),
                                                        ),
                                                    ),
                                                ),
                                                Li(
                                                    classs="""product-filters-tab""",
                                                    data=(
                                                        A(
                                                            href="""#""",
                                                            data=("""Color""",),
                                                        ),
                                                        Ul(
                                                            classs="""categories-menu menu vertical nested""",
                                                            data=(
                                                                A(
                                                                    href="""#""",
                                                                    classs="""clear-all""",
                                                                    id="""color-clear-all""",
                                                                    data=(
                                                                        """Clear All""",
                                                                    ),
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            id="""color-checkbox1""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""color-checkbox1""",
                                                                            data=(
                                                                                """All Color""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            id="""color-checkbox2""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""color-checkbox2""",
                                                                            data=(
                                                                                """Black""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            id="""color-checkbox3""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""color-checkbox3""",
                                                                            data=(
                                                                                """White""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            id="""color-checkbox4""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""color-checkbox4""",
                                                                            data=(
                                                                                """Grey""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            id="""color-checkbox5""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""color-checkbox5""",
                                                                            data=(
                                                                                """Red""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            id="""color-checkbox6""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""color-checkbox6""",
                                                                            data=(
                                                                                """Blue""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            id="""color-checkbox7""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""color-checkbox7""",
                                                                            data=(
                                                                                """Green""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            id="""color-checkbox8""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""color-checkbox8""",
                                                                            data=(
                                                                                """Purple""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            id="""color-checkbox8""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""color-checkbox8""",
                                                                            data=(
                                                                                """Multi-color""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                            ),
                                                        ),
                                                    ),
                                                ),
                                                Li(
                                                    classs="""product-filters-tab""",
                                                    data=(
                                                        A(
                                                            href="""#""",
                                                            data=("""Price""",),
                                                        ),
                                                        Ul(
                                                            classs="""categories-menu menu vertical nested""",
                                                            data=(
                                                                A(
                                                                    href="""#""",
                                                                    classs="""clear-all""",
                                                                    id="""price-clear-all""",
                                                                    data=(
                                                                        """Clear All""",
                                                                    ),
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            id="""price-checkbox1""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""price-checkbox1""",
                                                                            data=(
                                                                                """Under $25""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            id="""price-checkbox2""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""price-checkbox2""",
                                                                            data=(
                                                                                """$25–$50""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            id="""price-checkbox3""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""price-checkbox3""",
                                                                            data=(
                                                                                """$50–$250""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            id="""price-checkbox4""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""price-checkbox4""",
                                                                            data=(
                                                                                """$250–$600""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                                Li(
                                                                    data=(
                                                                        Input(
                                                                            id="""price-checkbox4""",
                                                                            typee="""checkbox""",
                                                                        ),
                                                                        Label(
                                                                            forr="""price-checkbox4""",
                                                                            data=(
                                                                                """$600–$1,000""",
                                                                            ),
                                                                        ),
                                                                    )
                                                                ),
                                                            ),
                                                        ),
                                                    ),
                                                ),
                                            ),
                                        ),
                                    )
                                ),
                            ),
                        ),
                        H1(
                            classs="""product-filters-header hide-for-small-only""",
                            data=("""Products""",),
                        ),
                        Ul(
                            classs="""vertical menu hide-for-small-only""",
                            data_accordion_menu="",
                            data=(
                                Li(
                                    classs="""product-filters-tab""",
                                    data=(
                                        A(href="""#""", data=("""Category""",)),
                                        Ul(
                                            classs="""categories-menu menu vertical nested is-active""",
                                            data=(
                                                A(
                                                    href="""#""",
                                                    classs="""clear-all""",
                                                    id="""category-clear-all""",
                                                    data=("""Clear All""",),
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""category-checkbox1""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""category-checkbox1""",
                                                            data=("""Category 1""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""category-checkbox2""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""category-checkbox2""",
                                                            data=("""Category 2""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""category-checkbox3""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""category-checkbox3""",
                                                            data=("""Category 3""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""category-checkbox4""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""category-checkbox4""",
                                                            data=("""Category 4""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""category-checkbox5""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""category-checkbox5""",
                                                            data=("""Category 5""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""category-checkbox6""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""category-checkbox6""",
                                                            data=("""Category 6""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""category-checkbox7""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""category-checkbox7""",
                                                            data=("""Category 7""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""category-checkbox8""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""category-checkbox8""",
                                                            data=("""Category 8""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""category-checkbox9""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""category-checkbox9""",
                                                            data=("""Category 9""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""category-checkbox10""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""category-checkbox10""",
                                                            data=("""Category 10""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""category-checkbox11""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""category-checkbox11""",
                                                            data=("""Category 11""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""category-checkbox12""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""category-checkbox12""",
                                                            data=("""Category 12""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""category-checkbox13""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""category-checkbox13""",
                                                            data=("""Category 13""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""category-checkbox14""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""category-checkbox14""",
                                                            data=("""Category 14""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""category-checkbox15""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""category-checkbox15""",
                                                            data=("""Category 15""",),
                                                        ),
                                                    )
                                                ),
                                            ),
                                        ),
                                    ),
                                ),
                                Li(
                                    classs="""product-filters-tab""",
                                    data=(
                                        A(href="""#""", data=("""Size""",)),
                                        Ul(
                                            classs="""categories-menu menu vertical nested is-active""",
                                            data=(
                                                A(
                                                    href="""#""",
                                                    classs="""clear-all""",
                                                    id="""size-clear-all""",
                                                    data=("""Clear All""",),
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""size-checkbox1""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""size-checkbox1""",
                                                            data=("""Small""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""size-checkbox2""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""size-checkbox2""",
                                                            data=("""Medium""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""size-checkbox3""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""size-checkbox3""",
                                                            data=("""Large""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""size-checkbox3""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""size-checkbox3""",
                                                            data=("""X-Large""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""size-checkbox3""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""size-checkbox3""",
                                                            data=("""XX-Large""",),
                                                        ),
                                                    )
                                                ),
                                            ),
                                        ),
                                    ),
                                ),
                                Li(
                                    classs="""product-filters-tab""",
                                    data=(
                                        A(href="""#""", data=("""Color""",)),
                                        Ul(
                                            classs="""categories-menu menu vertical nested""",
                                            data=(
                                                A(
                                                    href="""#""",
                                                    classs="""clear-all""",
                                                    id="""color-clear-all""",
                                                    data=("""Clear All""",),
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""color-checkbox1""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""color-checkbox1""",
                                                            data=("""All Color""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""color-checkbox2""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""color-checkbox2""",
                                                            data=("""Black""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""color-checkbox3""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""color-checkbox3""",
                                                            data=("""White""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""color-checkbox4""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""color-checkbox4""",
                                                            data=("""Grey""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""color-checkbox5""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""color-checkbox5""",
                                                            data=("""Red""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""color-checkbox6""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""color-checkbox6""",
                                                            data=("""Blue""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""color-checkbox7""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""color-checkbox7""",
                                                            data=("""Green""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""color-checkbox8""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""color-checkbox8""",
                                                            data=("""Purple""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""color-checkbox8""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""color-checkbox8""",
                                                            data=("""Multi-color""",),
                                                        ),
                                                    )
                                                ),
                                            ),
                                        ),
                                    ),
                                ),
                                Li(
                                    classs="""product-filters-tab""",
                                    data=(
                                        A(href="""#""", data=("""Price""",)),
                                        Ul(
                                            classs="""categories-menu menu vertical nested""",
                                            data=(
                                                A(
                                                    href="""#""",
                                                    classs="""clear-all""",
                                                    id="""price-clear-all""",
                                                    data=("""Clear All""",),
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""price-checkbox1""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""price-checkbox1""",
                                                            data=("""Under $25""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""price-checkbox2""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""price-checkbox2""",
                                                            data=("""$25–$50""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""price-checkbox3""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""price-checkbox3""",
                                                            data=("""$50–$250""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""price-checkbox4""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""price-checkbox4""",
                                                            data=("""$250–$600""",),
                                                        ),
                                                    )
                                                ),
                                                Li(
                                                    data=(
                                                        Input(
                                                            id="""price-checkbox4""",
                                                            typee="""checkbox""",
                                                        ),
                                                        Label(
                                                            forr="""price-checkbox4""",
                                                            data=("""$600–$1,000""",),
                                                        ),
                                                    )
                                                ),
                                            ),
                                        ),
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
            )
        ),
    )
)
