name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  build-n-publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Upgrade pip and install tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine uv

      - name: Build the package
        run: uv build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_TOKEN }}
